### ISSUE TITLE
这种错误有问题吗

### ISSUE THREAD

**Issue by dizzy-mihu** [ygxiuming/QN-big-study#18]
0%|          | 0/23 [00:00<?, ?it/s]───────────────────────────────────────────────────────────────────────────────
2023年第19期
NID: N0013000710181003
Name: 李天池
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connectionpool.py", line 371, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7890): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\study_20230812.py", line 333, in historystudy
    userid, name, info = get_person_info(token)
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\study_20230812.py", line 178, in get_person_info
    response = requests.request("GET", url, headers=config.headers,timeout=5)
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7890): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\study_20230812.py", line 410, in <module>
    historystudy(token, nid, name, id, tittle, subOrg, url,tittle_list)
  File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\study_20230812.py", line 341, in historystudy
    logging.error("main 函数出现错误，错误为：", e)
Message: 'main 函数出现错误，错误为：'
Arguments: (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=7890): Read timed out. (read timeout=5)")),)
  4%|▍         | 1/23 [00:05<01:53,  5.16s/it]───────────────────────────────────────────────────────────────────────────────
───────────────────────────────────────────────────────────────────────────────

**Comment by ygxiuming** [comment]
你重新运行试试，是每次都卡在这里吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月25日(周三) 晚上11:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ygxiuming/QN-big-study] 这种错误有问题吗 (Issue #18)




 
0%|          | 0/23 [00:00<?, ?it/s]───────────────────────────────────────────────────────────────────────────────
 2023年第19期
 NID: N0013000710181003
 Name: 李天池
 --- Logging error ---
 Traceback (most recent call last):
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connectionpool.py", line 537, in _make_request
 response = conn.getresponse()
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connection.py", line 461, in getresponse
 httplib_response = super().getresponse()
 File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1374, in getresponse
 response.begin()
 File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 318, in begin
 version, status, reason = self._read_status()
 File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 279, in _read_status
 line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
 File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\socket.py", line 705, in readinto
 return self._sock.recv_into(b)
 TimeoutError: timed out
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\requests\adapters.py", line 486, in send
 resp = conn.urlopen(
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
 retries = retries.increment(
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\util\retry.py", line 470, in increment
 raise reraise(type(error), error, _stacktrace)
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\util\util.py", line 39, in reraise
 raise value
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
 response = self._make_request(
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connectionpool.py", line 539, in _make_request
 self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\urllib3\connectionpool.py", line 371, in _raise_timeout
 raise ReadTimeoutError(
 urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=7890): Read timed out. (read timeout=5)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\study_20230812.py", line 333, in historystudy
 userid, name, info = get_person_info(token)
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\study_20230812.py", line 178, in get_person_info
 response = requests.request("GET", url, headers=config.headers,timeout=5)
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\requests\api.py", line 59, in request
 return session.request(method=method, url=url, **kwargs)
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\requests\sessions.py", line 589, in request
 resp = self.send(prep, **send_kwargs)
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\requests\sessions.py", line 703, in send
 r = adapter.send(request, **kwargs)
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\venv\lib\site-packages\requests\adapters.py", line 532, in send
 raise ReadTimeout(e, request=request)
 requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=7890): Read timed out. (read timeout=5)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\logging_init_.py", line 1100, in emit
 msg = self.format(record)
 File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\logging_init_.py", line 943, in format
 return fmt.format(record)
 File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\logging_init_.py", line 678, in format
 record.message = record.getMessage()
 File "C:\Users\mihu\AppData\Local\Programs\Python\Python310\lib\logging_init_.py", line 368, in getMessage
 msg = msg % self.args
 TypeError: not all arguments converted during string formatting
 Call stack:
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\study_20230812.py", line 410, in 
 historystudy(token, nid, name, id, tittle, subOrg, url,tittle_list)
 File "C:\Users\mihu\Desktop\QN-big-study-main(3)\QN-big-study-main\study_20230812.py", line 341, in historystudy
 logging.error("main 函数出现错误，错误为：", e)
 Message: 'main 函数出现错误，错误为：'
 Arguments: (ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='127.0.0.1', port=7890): Read timed out. (read timeout=5)")),)
 4%|▍         | 1/23 [00:05<01:53,  5.16s/it]───────────────────────────────────────────────────────────────────────────────
 ───────────────────────────────────────────────────────────────────────────────
